#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################


df -P / | grep / | awk '{ print $5}' | sed 's/%//g'

_create_service_notify_file(){
    mkdir -p /var/hostvn/telegram
    cat >> "/var/hostvn/telegram/diskNotify.sh" << END
#!/bin/sh

USERID="$TELEGRAM_ID"
KEY="$TELEGRAM_KEY"
TIMEOUT="10"
THRESHOLD=90
URL="https://api.telegram.org/bot\$KEY/sendMessage"
DATE_EXEC="\$(date "+%d %b %Y %H:%M")"
DISK_CURRENT=\$(df -P / | grep / | awk '{ print $5}' | sed 's/%//g')

if [ \$DISK_CURRENT >= \$THRESHOLD ]; then
    TEXT="\$DATE_EXEC: CANH BAO - VPS da su dung \${DISK_CURRENT}% dung luong."
    curl -s --max-time \$TIMEOUT -d "chat_id=\$USERID&disable_web_page_preview=1&text=\$TEXT" \$URL > /dev/null
fi
END
}
