#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

trigger=5.00
load=$(cat /proc/loadavg | awk '{print $1}')
response=$(echo | awk -v T=$trigger -v L="$load" 'BEGIN{if ( L > T){ print "greater"}}')

if [[ "$response" == "greater" ]]; then
    sar -q | mail -s"High load on server - [ $load ]" recipient@example.com
fi
