#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_update(){
    _cd_dir "${DEFAULT_DIR_TOOL}"/opcache
    rm -rf ./*
    wget -q https://raw.githubusercontent.com/amnuts/opcache-gui/master/index.php -O  "${DEFAULT_DIR_TOOL}"/opcache/index.php &> /dev/null
    chown -R nginx:nginx "${DEFAULT_DIR_TOOL}"/opcache
    clear
    printf "%s\n" "${GREEN}Update Opcache Dashboard success.${NC}"
}

_update
menu_admin_tool
