#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_set_var(){
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    PHPMYADMIN_VERSION=$(curl -s "${UPDATE_LINK}"/version | grep "phpmyadmin_version=" | cut -f2 -d'=')

    if [ "${php1_version}" == '5.6' ]; then
        PHPMYADMIN_VERSION=$(curl -s "${UPDATE_LINK}"/version | grep "phpmyadmin4_version=" | cut -f2 -d'=')
    fi
}

_update(){
    if [ -f /usr/share/nginx/private ]; then
        rm -rf /usr/share/nginx/private
    fi
    if [ ! -d /usr/share/nginx/private ]; then
        mkdir -p /usr/share/nginx/private
    fi
    _cd_dir "${DEFAULT_DIR_TOOL}"
    rm -rf phpmyadmin
    wget -O- "${HOMEPAGE_LINK}"/modules/phpMyAdmin-"${PHPMYADMIN_VERSION}"-english.tar.gz | tar -xz

    mv phpMyAdmin-"${PHPMYADMIN_VERSION}"-english phpmyadmin
    rm -rf "${DEFAULT_DIR_TOOL}"/phpmyadmin/setup
    chown -R nginx. "${DEFAULT_DIR_TOOL}"/phpmyadmin
}

_config_phpmyadmin(){
    blowfish_secret=$(date +%s%N | sha256sum | base64 | head -c 82)
    rm -rf "${DEFAULT_DIR_TOOL}"/phpmyadmin/setup
    mkdir -p "${DEFAULT_DIR_TOOL}"/phpmyadmin/tmp

    if [ "${php1_version}" != '5.6' ]; then
        declare="declare(strict_types=1);"
    fi

    cat >> "${DEFAULT_DIR_TOOL}/phpmyadmin/config.inc.php" <<EOCONFIGINC
<?php
${declare}
\$cfg['blowfish_secret'] = '${blowfish_secret}';
\$i = 0;
\$i++;
\$cfg['Servers'][\$i]['auth_type'] = 'cookie';
\$cfg['Servers'][\$i]['host'] = 'localhost';
\$cfg['Servers'][\$i]['connect_type'] = 'tcp';
\$cfg['Servers'][\$i]['compress'] = false;
\$cfg['Servers'][\$i]['AllowNoPassword'] = false;
\$cfg['UploadDir'] = '';
\$cfg['SaveDir'] = '';
\$cfg['PmaNoRelation_DisableWarning'] = true;
\$cfg['VersionCheck'] = false;
\$cfg['TempDir'] = '${DEFAULT_DIR_TOOL}/phpmyadmin/tmp';
\$cfg['CaptchaLoginPublicKey'] = '';
\$cfg['CaptchaLoginPrivateKey'] = '';
\$cfg['ExecTimeLimit'] = 600;
\$cfg['DefaultCharset'] = 'utf8';
\$cfg['DefaultConnectionCollation'] = 'utf8_general_ci';
EOCONFIGINC

    chown -R nginx:nginx "${DEFAULT_DIR_TOOL}"/phpmyadmin
}

_run(){
    _set_var

    _update
    _config_phpmyadmin
    if nginx -t; then
        systemctl reload nginx
        systemctl restart php"${php1_version}"-fpm
        if [ "${php2_release}" == "yes" ]; then
            systemctl restart php"${php2_version}"-fpm
        fi
        clear
        printf "%s\n" "${GREEN}Update phpMyAdmin success.${NC}"
    else
        nginx -t
        printf "%s\n" "${RED}${lang_error_vhost}${NC}"
        printf "%s\n" "${RED}${lang_use_rewrite_config}${NC}"
    fi
}

_run
menu_admin_tool
