#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=====================================%s\n" "${GREEN}" "${NC}"
printf "%s             Backup/Restore          %s\n" "${GREEN}" "${NC}"
printf "%s=====================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]; do
    printf "%s1. ${lang_backup}%s\n" "${GREEN}" "${NC}"
    printf "%s2. ${lang_restore}%s\n" "${GREEN}" "${NC}"
    printf "%s3. ${lang_delete_backup}%s\n" "${GREEN}" "${NC}"
    printf "%s4. ${lang_connect_gg_drive}%s\n" "${GREEN}" "${NC}"
    printf "%s5. ${lang_delete_connect_gg_drive}%s\n" "${GREEN}" "${NC}"
    printf "%s6. Connect Onedrive%s\n" "${GREEN}" "${NC}"
    printf "%s7. ${lang_auto_backup}%s\n" "${GREEN}" "${NC}"
    printf "%s====================================%s\n" "${GREEN}" "${NC}"
    read -r -p " ${SELECT_OPTION} " CHOICE
    if [ -z "${CHOICE}" ]; then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
    1)
        clear
        backup_data
        ;;
    2)
        clear
        restore_data
        ;;
    3)
        clear
        delete_backup
        ;;
    4)
        clear
        connect_google_drive
        ;;
    5)
        clear
        delete_connect_google_drive
        ;;
    6)
        clear
        connect_onedrive
        ;;
    7)
        clear
        menu_cronjob
        ;;
    0)
        clear
        menu_primary
        ;;
    *)
        clear
        printf "%s\n" "${RED}${WRONG_OPTION}${NC}"
        ;;
    esac
done
