#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s====================%s\n" "${GREEN}" "${NC}"
printf "    %sCache manager%s   \n" "${GREEN}" "${NC}"
printf "%s====================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Memcached%s\n" "${GREEN}" "${NC}"
    printf "%s2. Redis cache%s\n" "${GREEN}" "${NC}"
    printf "%s3. PHP Opcache%s\n" "${GREEN}" "${NC}"
    printf "%s4. Delete cache%s\n" "${GREEN}" "${NC}"
    printf "%s5. Nginx fastcgi cache%s\n" "${GREEN}" "${NC}"
    printf "%s=====================================%s\n" "${GREEN}" "${NC}"
    read -r -p " ${SELECT_OPTION} " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; cache_manage_memcached ;;
        2) clear; cache_manage_redis ;;
        3) clear; cache_manage_opcache ;;
        4) clear; cache_clear_cache ;;
        5) clear; cache_fastcgi ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}${WRONG_OPTION}${NC}";;
    esac
done
