#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=====================================%s\n" "${GREEN}" "${NC}"
printf "%s          Quan ly Domain             %s\n" "${GREEN}" "${NC}"
printf "%s=====================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]; do
    printf "%s1. ${lang_list_domain}%s\n" "${GREEN}" "${NC}"
    printf "%s2. ${lang_add_domain}%s\n" "${GREEN}" "${NC}"
    printf "%s3. ${lang_delete_domain}%s\n" "${GREEN}" "${NC}"
    printf "%s4. ${lang_change_domain}%s\n" "${GREEN}" "${NC}"
    printf "%s5. Rewrite Vhost Config%s\n" "${GREEN}" "${NC}"
    printf "%s6. Parked/Alias domain%s\n" "${GREEN}" "${NC}"
    printf "%s7. Redirect domain%s\n" "${GREEN}" "${NC}"
    printf "%s8. ${lang_change_website_php_version}%s\n" "${GREEN}" "${NC}"
    printf "%s9. Clone website%s\n" "${GREEN}" "${NC}"
    printf "%s10. ${lang_change_website_db_info}%s\n" "${GREEN}" "${NC}"
    printf "%s11. ${lang_change_sftp_pass}%s\n" "${GREEN}" "${NC}"
    printf "%s12. ${lang_protect_dir}%s\n" "${GREEN}" "${NC}"
    printf "%s======================================%s\n" "${GREEN}" "${NC}"
    read -r -p " ${SELECT_OPTION} " CHOICE
    if [ -z "${CHOICE}" ]; then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
    1)
        clear
        domain_list
        ;;
    2)
        clear
        domain_create
        ;;
    3)
        clear
        domain_delete
        ;;
    4)
        clear
        domain_change
        ;;
    5)
        clear
        domain_rewrite_config
        ;;
    6)
        clear
        domain_alias
        ;;
    7)
        clear
        domain_redirect
        ;;
    8)
        clear
        domain_change_php_version
        ;;
    9)
        clear
        domain_clone_website
        ;;
    10)
        clear
        domain_change_database_info
        ;;
    11)
        clear
        domain_change_pass_sftp
        ;;
    12)
        clear
        domain_protect_dir
        ;;
    0)
        clear
        menu_primary
        ;;
    *)
        clear
        printf "%s\n" "${RED}${WRONG_OPTION}${NC}"
        ;;
    esac
done
