#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s========================================%s\n" "${GREEN}" "${NC}"
printf "%s            Telegram Notify             %s\n" "${GREEN}" "${NC}"
printf "%s========================================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. Notify SSH Login%s\n" "${GREEN}" "${NC}"
    printf "%s2. Notify Service (Nginx, MariaDB, PHP)%s\n" "${GREEN}" "${NC}"
    printf "%s3. Notify Disk Usage%s\n" "${GREEN}" "${NC}"
    printf "%s4. Delete notify%s\n" "${GREEN}" "${NC}"
    printf "%s========================================%s\n" "${GREEN}" "${NC}"
    read -r -p " ${SELECT_OPTION} " CHOICE
    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) clear; telegram_ssh_notify;;
        2) clear; telegram_service_notify ;;
        3) clear; telegram_disk_notify ;;
        4) clear; telegram_delete_notify ;;
        0) clear; menu_tools ;;
        *) clear; printf "%s\n" "${RED}${WRONG_OPTION}${NC}";;
    esac
done
