#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

CHOICE=1

printf "%s=============================%s\n" "${GREEN}" "${NC}"
printf "          %sChown/Chmod%s        \n" "${GREEN}" "${NC}"
printf "%s=============================%s\n" "${GREEN}" "${NC}"

while [ "${CHOICE}" != "0" ]
do
    printf "%s1. ${lang_chmod_one_website}%s\n" "${GREEN}" "${NC}"
    printf "%s2. ${lang_chmod_all_website}%s\n" "${GREEN}" "${NC}"
    printf "%s============================%s\n" "${GREEN}" "${NC}"
    read -r -p " ${SELECT_OPTION} " CHOICE

    if [ -z "${CHOICE}" ]
    then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
        1) permission_one ;;
        2) permission_all ;;
        0) clear; menu_primary ;;
        *) clear; printf "%s\n" "${RED}${WRONG_OPTION}${NC}";;
    esac
done
