#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/route/parent
source /var/hostvn/menu/validate/rule

CHOICE=1
redis_status=$(pgrep redis >/dev/null && printf "%s\n" "${GREEN}Hoat dong${NC}" || printf "%s\n" "${GREEN}Khong hoat dong${NC}")

if [ ! -f "/lib/systemd/system/redis-server.service" ]; then
    redis_status="Chua cai dat"
fi

printf "${GREEN}%s${NC}\n" "====================="
printf "${GREEN}%s${NC}\n" "Quan ly Redis Cache"
printf "${GREEN}%s${NC}\n" "${GREEN}Trang thai:${NC} ${redis_status}"
printf "${GREEN}%s${NC}\n" "====================="

while [ "${CHOICE}" != "0" ]; do
    printf "${GREEN}%s${NC}\n" "1. Bat Redis Cache"
    printf "${GREEN}%s${NC}\n" "2. Tat Redis Cache"
    printf "${GREEN}%s${NC}\n" "3. Cai dat Redis cache"
    printf "${GREEN}%s${NC}\n" "4. Go bo Redis Cache"
    printf "${GREEN}%s${NC}\n" "======================"
    read -r -p " Nhap vao lua chon cua ban [0 = Thoat] " CHOICE

    if [ -z "${CHOICE}" ]; then
        CHOICE=1
        continue
    fi
    case ${CHOICE} in
    1)
        if [ ! -f "/lib/systemd/system/redis-server.service" ]; then
            clear
            printf "%s\n" "${RED}Redis chua duoc cai dat.${NC}"
        elif service_running "memcached"; then
            clear
            printf "${RED}%s${NC}\n" "Memcached dang hoat dong. Ban chi nen su dung mot loai cache."
        elif service_running "redis"; then
            clear
            printf "${RED}%s${NC}\n" "Redis dang hoat dong."
        else
            printf "%s\n" "${GREEN}Dang tien hanh mo Redis Cache...${NC}"
            sleep 1
            systemctl enable redis.service
            systemctl start redis.service
            cron_exists=$(crontab -l | grep -w 'redis')
            if [ -z "${cron_exists}" ]; then
                crontab -l >clear_redis
                echo "23 */38 * * * systemctl restart redis >/dev/null 2>&1" >>clear_redis
                crontab clear_redis
                rm -rf clear_redis
            fi
            clear
            printf "%s\n" "${GREEN}Da bat Redis Cache.${NC}"
        fi
        cache_manage_redis
        ;;
    2)
        if service_running "redis"; then
            printf "%s\n" "${GREEN}Dang tien hanh tat Redis Cache...${NC}"
            sleep 1
            systemctl stop redis.service
            systemctl disable redis.service
            cron_exists=$(crontab -l | grep -w 'redis')
            if [ -n "${cron_exists}" ]; then
                crontab -u root -l | grep -v "redis" | crontab -u root -
            fi
            clear
            printf "%s\n" "${GREEN}Da tat Redis Cache.${NC}"
        else
            clear
            printf "%s\n" "${RED}Redis cache hien khong hoat dong.${NC}"
        fi

        cache_manage_redis
        ;;
    3) cache_install_redis ;;
    4)
        if [ -f "/lib/systemd/system/redis-server.service" ]; then
            systemctl stop redis
            apt-get purge --auto-remove redis-server -y
            apt autoremove -y
            rm -rf /etc/redis
            cron_exists=$(crontab -l | grep -w 'redis')
            if [ -n "${cron_exists}" ]; then
                crontab -u root -l | grep -v "redis" | crontab -u root -
            fi
            systemctl daemon-reload
            clear
            printf "${GREEN}%s\n${NC}" "Go bo Redis thanh cong."
        else
            clear
            printf "${RED}%s\n${NC}" "Redis chua duoc cai dat."
        fi
        cache_manage_redis
        ;;
    0)
        clear
        menu_cache
        ;;
    *)
        clear
        printf "%s\n" "${RED}Lua chon cua ban khong chinh xac. Vui long chon lai.${NC}"
        ;;
    esac
done
