#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_set_var() {
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    php_version=$(grep -w "php_version" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_user=$(grep -w "db_user" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_password=$(grep -w "db_password" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    php_version=$(grep -w "php_version" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    user_pass=$(grep -w "user_pass" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    htpasswd_user=$(grep -w "htpasswd_user" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    htpasswd_passwd=$(grep -w "htpasswd_passwd" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
}

_show_info() {
    printf "1.  Phien ban PHP dang chay    : %s\n" "${php_version}"
    printf "2.  Domain                     : %s\n" "${domain}"
    printf "3.  DB_Name                    : %s\n" "${db_name}"
    printf "4.  DB_User                    : %s\n" "${db_user}"
    printf "5.  DB_Password                : %s\n" "${db_password}"
    printf "6.  Username (SFTP)            : %s\n" "${user}"
    printf "7.  Password (SFTP)            : %s\n" "${user_pass}"
    printf "8.  SFTP Host                  : %s\n" "${IPADDRESS}"
    printf "9.  SFTP Port                  : %s\n" "${ssh_port}"
    printf "10.  Public_html               : %s\n" "/home/${user}/${domain}/public_html"
    printf "11. Nginx vHost                : %s\n" "/etc/nginx/conf.d/${domain}.conf"
    printf "12. PHP config                 : %s\n" "/etc/php/${php_version}/fpm/pool.d/${domain}.conf"
    if [ -n "${htpasswd_user}" ]; then
        printf "13.  HTTP Authenticate User    : %s\n" "${htpasswd_user}"
    fi
    if [ -n "${htpasswd_passwd}" ]; then
        printf "14. HTTP Authenticate password : %s\n" "${htpasswd_passwd}"
    fi
}

domain=""
ALERT=""

_select_domain
if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}${lang_cancel_action}${NC}"
else
    if [ -z "${ALERT}" ]; then
        clear
        _set_var
        _show_info
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_account
