#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_select_cf_action() {
    clear
    printf "%s\n" "Lua chon thao tac ban muon thuc hien"
    PS3="Nhap vao lua chon cua ban [ 1 - 3 ]: "
    options=("Cau hinh CF API" "Xoa CF API" "Cancel")
    select opt_cf in "${options[@]}"; do
        case $opt_cf in
        "Cau hinh CF API")
            action="enable"
            break
            ;;
        "Xoa CF API")
            action="disable"
            break
            ;;
        "Cancel")
            action="cancel"
            break
            ;;
        *) printf "${RED}%s${NC}\n" "Lua chon cua ban khong chinh xac. Vui long chon lai. $REPLY" ;;
        esac
    done
}

_enable_cf_api() {
    if [ -f "/root/.acme.sh/account.conf" ]; then
        check_cf_config=$(grep -w "CF_Key" "/root/.acme.sh/account.conf")
        if [ -z "${check_cf_config}" ]; then
            read -r -p "Nhap vao CF Token [0 = thoat]: " cf_token


            if [[ -n "${cf_token}" && "${cf_token}" != 0 ]]; then
                read -r -p "Nhap vao Email dang nhap CloudFlare [0 = thoat]: " cf_email

                if [[ -n "${cf_email}" && "${cf_email}" != 0 ]]; then
                    cat >>"/root/.acme.sh/account.conf" <<END
CF_Key="${cf_token}"
CF_Email="${cf_email}"
END
                    notify="${GREEN}Cau hinh thanh cong. Vui long thoat SSH va login lai de cau hinh co hieu luc.${NC}"
                else
                    notify="${RED}Huy thao tac.${NC}"
                fi
            else
                notify="${RED}Huy thao tac.${NC}"
            fi
        else
            notify="${RED}Ban da cau hinh CF DNS API. Neu muon cau hinh lai vui long xoa cau hinh cu truoc.${NC}"
        fi
    else
        notify="${RED}Cau hinh that bai. Vui long dam bao acme.sh da duoc cai dat.${NC}"
    fi

    clear
    printf "%s\n" "${notify}"
}

_disable_cf_api() {
    if [ -f "/root/.acme.sh/account.conf" ]; then
        check_cf_config=$(grep -w "CF_Key" "/root/.acme.sh/account.conf")
        if [ -n "${check_cf_config}" ]; then
            while true; do
                read -r -p "Ban muon xoa cau hinh CloudFlare API ? (y/n) " promt_disable_cf
                sleep 3
                echo
                if [[ "${promt_disable_cf}" =~ ^([yY])$ || "${promt_disable_cf}" =~ ^([nN])$ ]]; then
                    break
                else
                    printf "%s\n" "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
                fi
            done

            if [[ "${promt_disable_cf}" =~ ^([yY])$ ]]; then
                sed -i "/CF_Key/d" /root/.acme.sh/account.conf
                sed -i "/CF_Email/d" /root/.acme.sh/account.conf
                #                sed -i "/CF_Account_ID/d" /root/.acme.sh/account.conf
                #                sed -i "/CF_Zone_ID/d" /root/.acme.sh/account.conf
                notify="${GREEN}Xoa cau hinh thanh cong.${NC} ${RED}Vui long thoat SSH va login lai de cau hinh co hieu luc.${NC}"
            else
                notify="${RED}Huy thao tac.${NC}"
            fi
        else
            notify="${RED}Ban chua cau hinh CloudFlare API.${NC}"
        fi
    else
        notify="${RED}Cau hinh that bai. Vui long dam bao acme.sh da duoc cai dat.${NC}"
    fi

    printf "%s\n" "${notify}"
}

action=""
notify=""
_select_cf_action

if [ "${action}" == "enable" ]; then
    _enable_cf_api
elif [ "${action}" == "disable" ]; then
    _disable_cf_api
else
    clear
    printf "%s\n" "${RED}Huy thao tac.${NC}"
fi

ssl_le
