#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_set_var() {
    #https://www.howtoforge.com/tutorial/linux-grep-command/
    #https://stackoverflow.com/a/6284370
    user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    db_name=$(grep -w "db_name" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
    new_admin_pwd=$(_gen_pass)
}

_backup_confirm() {
    while true; do
        read -r -p "Ban co muon backup du lieu truoc khi doi mat khau admin khong? (y/n) " prompt_backup
        echo
        if [[ "${prompt_backup}" =~ ^([yY])$ || "${prompt_backup}" =~ ^([nN])$ ]]; then
            break
        else
            clear
            printf "%s\n" "${RED}Gia tri ban nhap khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

_input() {
    while true; do
        read -r -p "Nhap ID cua tai khoan admin muon doi mat khau [0 = Thoat]: " admin_id
        echo
        if valid_number "${admin_id}"; then
            break
        else
            printf "%s\n" "${RED}Gia tri ban nhap khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

_backup() {
    _cd_dir /home/"${user}"/"${domain}"/public_html
    if [[ -f "/home/backup/${CURRENT_DATE}/${domain}/${db_name}.sql" ]]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${db_name}".sql
    fi
    if [[ -f "/home/backup/${CURRENT_DATE}/${domain}/${db_name}.sql.gz" ]]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${db_name}".sql.gz
    fi
    if [[ ! -d "/home/backup/${CURRENT_DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${CURRENT_DATE}"/"${domain}"
    fi

    _cd_dir /home/backup/"${CURRENT_DATE}"/"${domain}"
    mysqldump -uadmin -p"${mysql_pwd}" "${db_name}" | gzip >"${db_name}".sql.gz
}

_run() {
    _cd_dir /home/"${user}"/"${domain}"/public_html
    check_wpconfig "${user}" "${domain}"

    if [ -z "${ALERT}" ]; then
        clear
        echo "Lay danh sach User co quyen Admin tren website: "
        wp user list --role=administrator --fields=ID,user_login --allow-root
        _input
        if [ "${admin_id}" == "0" ]; then
            clear
            printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
        else
            wp user update "${admin_id}" --user_pass="${new_admin_pwd}" --allow-root
            if nginx -t; then
                _restart_service
                clear
                printf "%s\n" "${GREEN}Doi mat khau admin (wp-admin) thanh cong.${NC}"
                printf "%s\n" "${GREEN}Mat khau moi la:${NC} ${RED}${new_admin_pwd}${NC}"
            else
                clear
                nginx -t
                printf "%s\n" "${RED}${lang_error_vhost}${NC}"
                printf "%s\n" "${RED}${lang_use_rewrite_config}${NC}"
            fi
        fi
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
}

ALERT=""
prompt_backup=""
domain=""
admin_id=""
_select_wordpress_website
if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac.${NC}"
else
    _set_var
    _backup_confirm
    if [[ "${prompt_backup}" =~ ^([yY])$ ]]; then
        _backup
    fi
    _run
fi

menu_wordpress
