#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_select_htpasswd_action() {
    clear
    printf "%s\n" "Lua chon thao tac ban muon thuc hien"
    PS3="Nhap vao lua chon cua ban [ 1 - 3 ]: "
    options=("Disable htpasswd" "Enable htpasswd" "Cancel")
    select opt in "${options[@]}"; do
        case $opt in
        "Disable htpasswd")
            action="disable"
            break
            ;;
        "Enable htpasswd")
            action="enable"
            break
            ;;
        "Cancel")
            action="cancel"
            break
            ;;
        *) printf "${RED}%s${NC}\n" "Lua chon cua ban khong chinh xac. Vui long chon lai. $REPLY" ;;
        esac
    done
    sleep 1
}

_select_site_enable_htpasswd() {
    domain=""
    #https://www.cyberciti.biz/faq/linux-unix-shell-check-if-directory-empty/
    if [[ "$(ls -A "${USER_DIR}")" ]]; then
        domains=()
        echo "${LIST_DOMAIN}"
        _cd_dir "${USER_DIR}"
        #https://stackoverflow.com/a/2437466
        #https://stackoverflow.com/a/1951523
        #https://stackoverflow.com/a/46882842
        for entry in .*.conf; do
            domain=${entry/./}
            domain=${domain//.conf/}
            user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
            check_htpasswd_include=$(grep -w "htpasswd.conf" "${VHOST_DIR}/${domain}.conf")
            if [[ -d "/home/${user}/${domain}/public_html/wp-content" && -z "${check_htpasswd_include}" ]]; then
                domains+=("${domain}")
            fi
        done
        if [ ${#domains[@]} -eq 0 ]; then
            ALERT=$(printf "%s\n" "${RED}Tat ca cac website WordPress da duoc thiet lap bao mat hai lop.${NC}")
        else
            echo "Lua chon website"
            PS3="${INPUT_SELECT} [0 = Thoat]: "
            select opt in "${domains[@]}"; do
                domain=$opt
                break
            done
        fi
    else
        ALERT=$(printf "%s\n" "${RED}${EMPTY_DOMAIN}${NC}")
    fi
}

_select_site_disable_htpasswd() {
    domain=""
    #https://www.cyberciti.biz/faq/linux-unix-shell-check-if-directory-empty/
    if [[ "$(ls -A "${USER_DIR}")" ]]; then
        domains=()
        echo "${LIST_DOMAIN}"
        _cd_dir "${USER_DIR}"
        #https://stackoverflow.com/a/2437466
        #https://stackoverflow.com/a/1951523
        #https://stackoverflow.com/a/46882842
        for entry in .*.conf; do
            domain=${entry/./}
            domain=${domain//.conf/}
            user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
            check_htpasswd_include=$(grep -w "htpasswd.conf" "${VHOST_DIR}/${domain}.conf")
            if [[ -d "/home/${user}/${domain}/public_html/wp-content" && -n "${check_htpasswd_include}" ]]; then
                domains+=("${domain}")
            fi
        done

        if [ ${#domains[@]} -eq 0 ]; then
            ALERT=$(printf "%s\n" "${RED}Chua co website WordPress nao duoc thiet lap bao mat hai lop.${NC}")
        else
            echo "Lua chon website"
            PS3="${INPUT_SELECT} [0 = Thoat]: "
            select opt in "${domains[@]}"; do
                domain=$opt
                break
            done
        fi
    else
        ALERT=$(printf "%s\n" "${RED}${EMPTY_DOMAIN}${NC}")
    fi
}

_enable_htpasswd() {
    mkdir -p /home/"${user}"/"${domain}"/htpasswd/wp_admin

    read -r -p "Nhap vao user: " htpasswd_user
    read -r -p "Nhap vao mat khau: " htpasswd_passwd

    if [ -f "/home/${user}/${domain}/htpasswd/wp_admin/.htpasswd" ]; then
        rm -rf /home/"${user}"/"${domain}"/htpasswd/wp_admin/.htpasswd
    fi

    htpasswd -b -c /home/"${user}"/"${domain}"/htpasswd/wp_admin/.htpasswd "${htpasswd_user}" "${htpasswd_passwd}"

    #    if [ -f "/home/${user}/${domain}/htpasswd/wp_admin/htpasswd.conf" ]; then
    #        rm -rf /home/"${user}"/"${domain}"/htpasswd/wp_admin/htpasswd.conf
    #    fi
    chown -R "${user}":"${user}" /home/"${user}"/"${domain}"/htpasswd/
    chown -R "${user}":"${user}" /home/"${user}"/"${domain}"/htpasswd/wp_admin/.htpasswd

    #    cat >>"/home/${user}/${domain}/htpasswd/wp_admin/htpasswd.conf" << END
    #location /wp-admin {
    #    auth_basic "Prohibited Area";
    #    auth_basic_user_file /home/${user}/${domain}/htpasswd/wp_admin/.htpasswd;
    #}
    #END

    if [[ -f "/home/${user}/${domain}/htpasswd/wp_admin/.htpasswd" ]]; then
        #    if [[ -f "/home/${user}/${domain}/htpasswd/wp_admin/.htpasswd" && -f "/home/${user}/${domain}/htpasswd/wp_admin/htpasswd.conf" ]]; then
        check_php_cache=$(grep -w "php_cache.conf" "${VHOST_DIR}/${domain}.conf")
        check_php_cache_woo=$(grep -w "php_cache_woo.conf" "${VHOST_DIR}/${domain}.conf")
        rm -rf "${VHOST_DIR}"/"${domain}".conf

        if [ -f "${CUSTOM_DIR}/wordpress.conf" ]; then
            cp "${CUSTOM_DIR}"/wordpress.conf "${VHOST_DIR}"/"${domain}".conf
        else
            cp "${TEMPLATE_DIR}"/wordpress.conf "${VHOST_DIR}"/"${domain}".conf
        fi

        if [ -n "${check_php_cache}" ]; then
            sed -i "s|PHP_CONFIG|include ${NGINX_CONF_DIR}/php/${domain}/php_cache.conf;|g" "${VHOST_DIR}"/"${domain}".conf
        elif [ -n "${check_php_cache_woo}" ]; then
            sed -i "s|PHP_CONFIG|include ${NGINX_CONF_DIR}/php/${domain}/php_cache_woo.conf;|g" "${VHOST_DIR}"/"${domain}".conf
        else
            sed -i "s|PHP_CONFIG|include ${NGINX_CONF_DIR}/php/${domain}/php_no_cache.conf;|g" "${VHOST_DIR}"/"${domain}".conf
        fi
        sed -i "s|WEBSITE_USER|${user}|g" "${VHOST_DIR}"/"${domain}".conf
        sed -i "s|WEBSITE_DOMAIN|${domain}|g" "${VHOST_DIR}"/"${domain}".conf
        sed -i "s|WEBSITE_SOURCE|${SOURCE}|g" "${VHOST_DIR}"/"${domain}".conf

        if [[ -f "${SSL_DIR}/${domain}/key.pem" && -f "${SSL_DIR}/${domain}/cert.pem" && -s "${SSL_DIR}/${domain}/key.pem" && -s "${SSL_DIR}/${domain}/cert.pem" ]]; then
            expired_date=$(echo "(" "$(date -d "$(openssl x509 -in "${SSL_DIR}"/"${domain}"/cert.pem -text -noout | grep "Not After" | cut -c 25-)" +%s)" - "$(date -d "now" +%s)" ")" / 86400 | bc)
            if [[ -n ${expired_date} && ${expired_date} -gt 0 ]]; then
                sed -i '/return 404;/d' "${VHOST_DIR}"/"${domain}".conf
                sed -i '/error_page 404/d' "${VHOST_DIR}"/"${domain}".conf
                sed -i "/listen 80;/a include ${NGINX_CONF_DIR}/extra/https.conf;" "${VHOST_DIR}"/"${domain}".conf
                sed -i "s|ssl_certificate ${SSL_DIR}/server/server.crt;|ssl_certificate ${SSL_DIR}/${domain}/cert.pem;|g" "${VHOST_DIR}"/"${domain}".conf
                sed -i "s|ssl_certificate_key ${SSL_DIR}/server/server.key;|ssl_certificate_key ${SSL_DIR}/${domain}/key.pem;|g" "${VHOST_DIR}"/"${domain}".conf
            fi
        fi

        if [[ -f "${SSL_DIR}/${domain}/paid/key.pem" && -f "${SSL_DIR}/${domain}/paid/cert.pem" && -s "${SSL_DIR}/${domain}/paid/key.pem" && -s "${SSL_DIR}/${domain}/paid/cert.pem" ]]; then
            expired_date=$(echo "(" "$(date -d "$(openssl x509 -in "${SSL_DIR}"/"${domain}"/paid/cert.pem -text -noout | grep "Not After" | cut -c 25-)" +%s)" - "$(date -d "now" +%s)" ")" / 86400 | bc)
            if [[ -n ${expired_date} && ${expired_date} -gt 0 ]]; then
                sed -i '/return 404;/d' "${VHOST_DIR}"/"${domain}".conf
                sed -i '/error_page 404/d' "${VHOST_DIR}"/"${domain}".conf
                sed -i '/https.conf;/d' "${VHOST_DIR}"/"${domain}".conf
                sed -i "/listen 80;/a include ${NGINX_CONF_DIR}/extra/https.conf;" "${VHOST_DIR}"/"${domain}".conf
                sed -i "s|ssl_certificate ${SSL_DIR}/server/server.crt;|ssl_certificate ${SSL_DIR}/${domain}/paid/cert.pem;|g" "${VHOST_DIR}"/"${domain}".conf
                sed -i "s|ssl_certificate_key ${SSL_DIR}/server/server.key;|ssl_certificate_key ${SSL_DIR}/${domain}/paid/key.pem;|g" "${VHOST_DIR}"/"${domain}".conf
            fi
        fi

        plugin_seo=$(grep -w "plugin_seo" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
        if [ -n "${plugin_seo}" ]; then
            sed -i "s|PLUGIN_SEO|include ${NGINX_CONF_DIR}/wordpress/${plugin_seo}.conf;|g" "${VHOST_DIR}"/"${domain}".conf
        else
            sed -i '/PLUGIN_SEO/d' "${VHOST_DIR}"/"${domain}".conf
        fi

        plugin_cache=$(grep -w "plugin_cache" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
        if [[ -n "${plugin_cache}" && "${plugin_cache}" != "other" ]]; then
            if [[ "${plugin_cache}" == "wpfc" || "${plugin_cache}" == "wpsc" || "${plugin_cache}" == "enabler" ]]; then
                sed -i '/wordpress.conf/d' "${VHOST_DIR}"/"${domain}".conf
            fi
            sed -i '/staticfiles.conf/d' "${VHOST_DIR}"/"${domain}".conf
            if [ "${plugin_cache}" != "wprocket" ]; then
                sed -i "s|PLUGIN_CACHE|include ${NGINX_CONF_DIR}/wordpress/${plugin_cache}.conf;|g" "${VHOST_DIR}"/"${domain}".conf
            else
                sed -i "s|PLUGIN_CACHE|include ${NGINX_CONF_DIR}/rocket-nginx/default.conf;|g" "${VHOST_DIR}"/"${domain}".conf
            fi
        else
            sed -i '/PLUGIN_CACHE/d' "${VHOST_DIR}"/"${domain}".conf
        fi

        disable_xmlrpc=$(grep -w "disable_xmlrpc" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
        if [ "${disable_xmlrpc}" == "no" ]; then
            sed -i '/disable_xmlrpc.conf/d' "${VHOST_DIR}"/"${domain}".conf
        fi

        disable_user_api=$(grep -w "disable_user_api" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
        if [ "${disable_user_api}" == "no" ]; then
            sed -i '/disable_user_api.conf/d' "${VHOST_DIR}"/"${domain}".conf
        fi

        check_brute_force_config=$(grep -w "req_limit_per_ip" "${VHOST_DIR}/${domain}.conf")
        if [ -z "${check_brute_force_config}" ]; then
            sed -i "s|HTPASSWD|include /home/${user}/${domain}/htpasswd/wp_admin/htpasswd.conf;|g" "${VHOST_DIR}"/"${domain}".conf
            cat >>"/home/${user}/${domain}/htpasswd/wp_admin/htpasswd.conf" <<END
location = /wp-login.php {
    auth_basic "Prohibited Area";
    auth_basic_user_file /home/${user}/${domain}/htpasswd/wp_admin/.htpasswd;
    limit_req zone=req_limit_per_ip burst=1 nodelay;
    include ${NGINX_CONF_DIR}/fastcgi_params;
    include ${NGINX_CONF_DIR}/extra/nginx_limits.conf;
    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    if (-f \$request_filename)
    {
        fastcgi_pass php-${user};
    }
}
END
        else
            sed -i '/HTPASSWD/d' "${VHOST_DIR}"/"${domain}".conf
            sed -i "/limit_req/a auth_basic_user_file /home/${user}/${domain}/htpasswd/wp_admin/.htpasswd;" "${VHOST_DIR}"/"${domain}".conf
            sed -i "/limit_req/a auth_basic \"Prohibited Area\";" "${VHOST_DIR}"/"${domain}".conf
        fi

        if nginx -t; then
            _restart_service
            clear
            printf "%s\n" "Tao mat khau hai lop thanh cong."
        else
            clear
            nginx -t
            printf "%s\n" "${RED}${lang_error_vhost}${NC}"
            printf "%s\n" "${RED}${lang_use_rewrite_config}${NC}"
        fi
    else
        clear
        printf "%s\n" "Tao mat khau hai lop that bai."
    fi

}

_disable_htpasswd() {
    if [ -d "/home/${user}/${domain}/htpasswd/wp_admin" ]; then
        rm -rf /home/"${user}"/"${domain}"/htpasswd/wp_admin
    fi
    sed -i '/htpasswd.conf/d' "${VHOST_DIR}"/"${domain}".conf
    sed -i '/auth_basic/d' "${VHOST_DIR}"/"${domain}".conf
    sed -i '/auth_basic_user_file/d' "${VHOST_DIR}"/"${domain}".conf

    if nginx -t; then
        _restart_service
        clear
        printf "${GREEN}%s${NC}\n" "Xoa mat khau hai lop thanh cong."
    else
        clear
        nginx -t
        printf "%s\n" "${RED}${lang_error_vhost}${NC}"
        printf "%s\n" "${RED}${lang_use_rewrite_config}${NC}"
    fi
}

ALERT=""
domain=""
action=""

_select_htpasswd_action

if [[ -z "${action}" || "${action}" == "cancel" ]]; then
    clear
    printf "${RED}%s${NC}\n" "Huy thao tac."
else
    if [ "${action}" == "enable" ]; then
        _select_site_enable_htpasswd
    fi

    if [ "${action}" == "disable" ]; then
        _select_site_disable_htpasswd
    fi

    if [[ -z "${domain}" && -z "${ALERT}" ]]; then
        clear
        printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
    else
        if [ -z "${ALERT}" ]; then
            user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')

            if [ "${action}" == "enable" ]; then
                _enable_htpasswd
            fi
            if [ "${action}" == "disable" ]; then
                _disable_htpasswd
            fi
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    fi
fi

menu_wordpress
