#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
      user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
      mv /home/"${user}"/"${domain}"/public_html/wp-config.php /home/"${user}"/"${domain}"/wp-config.php
      clear
      printf "Di chuyen wp-config thanh cong.\n"
}

ALERT=""
domain=""

_select_wordpress_website

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_wordpress
