#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

rm -rf /etc/nginx/extra/cloudflare.conf

cat >>"/etc/nginx/extra/cloudflare.conf" <<EOCF
real_ip_header X-Forwarded-For;
EOCF

for ipv4 in `curl https://www.cloudflare.com/ips-v4` ; do
    cat >> "/etc/nginx/extra/cloudflare.conf" <<EOcf_ipv4
set_real_ip_from $ipv4;
EOcf_ipv4
done

for ipv6 in `curl https://www.cloudflare.com/ips-v6` ; do
    cat >> "/etc/nginx/extra/cloudflare.conf" <<EOcf_ipv6
set_real_ip_from $ipv6;
EOcf_ipv6
done
