#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_input(){
    while true
    do
        echo "Username khong chua ky tu dac biet va dai 5 - 8 ky tu."
        read -r -p "Nhap ten database [0 = Thoat]: " db_name
        echo
        if validate_user "${db_name}" || [ "${db_name}" == "0" ]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done

    if [ "${db_name}" != "0" ]; then
        while true
        do
            echo "Username khong chua ky tu dac biet va dai 5 - 8 ky tu."
            read -r -p "Nhap Mysql User [0 = Thoat]: " db_user
            echo
            if validate_user "${db_user}" || [ "${db_user}" == "0" ]; then
                break
            else
                printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
            fi
        done

        if [ "${db_user}" != "0" ]; then
            while true
            do
                read -r -p "Xac nhan them database? (y/n): " prompt_db
                echo
                if [[ "${prompt_db}" =~ ^([yY])$ || "${prompt_db}" =~ ^([nN])$ ]]; then
                    break
                else
                    printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
                fi
            done

            while true
            do
                read -r -p "Ban co muon tao mat khau random khong? (y/n): " prompt_pass
                echo
                if [[ "${prompt_pass}" =~ ^([yY])$ || "${prompt_pass}" =~ ^([nN])$ ]]; then
                    break
                else
                    printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
                fi
            done

            if [[ "${prompt_pass}" =~ ^([yY])$ ]]; then
                password=$(_gen_pass)
            else
                read -r -p "Nhap mat khau Database: " password
            fi
        fi
    fi
}

_validate(){
    check_database "${db_name}"
    check_mysql_user "${db_user}"
}

_create_db(){
    printf "%s\n" "${GREEN}Dang tao database moi...${NC}"
    Q1="CREATE DATABASE IF NOT EXISTS ${db_name} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
    Q2="CREATE USER IF NOT EXISTS '${db_user}'@'localhost' IDENTIFIED BY '$password';"
    Q3="GRANT ALL PRIVILEGES ON ${db_name}.* TO '${db_user}'@'localhost';"
    Q4="FLUSH PRIVILEGES;"
    SQL="${Q1}${Q2}${Q3}${Q4}"
    mysql -uadmin -p"${mysql_pwd}" -e "${SQL}"
    clear
    printf "%s\n" "${GREEN}Da them databse thanh cong.${NC}"
}

_show_info(){
    clear
    printf "DB_Name    : %s\n" "${RED}${db_name}${NC}"
    printf "DB_User    : %s\n" "${RED}${db_user}${NC}"
    printf "DB_Password: %s\n" "${RED}${password}${NC}"
    echo ""
    sleep 3
}

_run(){
    if [[ ${prompt_db} =~ ^([yY])$  ]]; then
       _validate

        if [ -z "${ALERT}" ]; then
            _create_db
            _show_info
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    else
        clear
        printf "%s\n" "${RED}Ban da huy them database.${NC}"
    fi
}

ALERT=""
prompt_db=""
db_name=""
db_user=""
_input "$@"

if [ "${db_name}" == "0" ]; then
    clear
    printf "%s\n" "${RED}Ban da huy them database.${NC}"
else
    if [ "${db_user}" == "0" ]; then
        clear
        printf "%s\n" "${RED}Ban da huy them database.${NC}"
    else
        _run "$@"
    fi
fi

lemp_database
