#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

printf "${GREEN}%s${NC}\n" "============"
printf "${GREEN}%s${NC}\n" "Xoa database"
printf "${GREEN}%s${NC}\n" "============"

_list_db(){
    echo "Danh sach Database tren VPS"
    mysql -uadmin -p"${mysql_pwd}" -e "SHOW DATABASES WHERE \`Database\` NOT IN('information_schema', 'phpmyadmin', 'mysql', 'performance_schema')"
    echo
}

_input(){
    while true
    do
        echo "Username khong chua ky tu dac biet va dai 5 - 8 ky tu."
        read -r -p "Nhap ten database [0 = Thoat]: " db_name
        echo
        if validate_user "${db_name}" || [ "${db_name}" == "0" ]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done

    if [ "${db_name}" != "0" ]; then
        while true
        do
            read -r -p "Xac nhan xoa database? (y/n): " prompt_destroy
            echo
            if [[ "${prompt_destroy}" =~ ^([yY])$ || "${prompt_destroy}" =~ ^([nN])$ ]]; then
                break
            else
                printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
            fi
        done
    fi
}

_delete_db(){
    if [[ "${prompt_destroy}" =~ ^([yY])$ ]]; then
        printf "%s\n" "${GREEN}Dang tien hanh xoa database...${NC}"
        sleep 1
        mysql -uadmin -p"${mysql_pwd}" -e "DROP DATABASE IF EXISTS ${db_name};"
        clear
        printf "%s\n" "${GREEN}Xoa database thanh cong.${NC}"
    else
        clear
        printf "%s\n" "${RED}Ban da huy xoa database.${NC}"
    fi
}

_run(){
    _list_db
    _input

    if [ "${db_name}" != "0" ]; then
        _delete_db
    else
        clear
        printf "%s\n" "${RED}Ban da huy xoa database.${NC}"
    fi

}

db_name=""
prompt_destroy=""

_run
lemp_database
