#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_select_action(){
    clear
    printf "%s\n" "Lua chon thao tac ban muon thuc hien"
    PS3="Nhap vao lua chon cua ban [ 1 - 3 ]: "
    options_image=("Enable compress image" "Disable compress image" "Cancel")
    select opt_img in "${options_image[@]}"; do
        case $opt_img in
        "Enable compress image")
            action="enable"
            break
            ;;
        "Disable compress image")
            action="disable"
            break
            ;;
        "Cancel")
            action="cancel"
            break
            ;;
        *) printf "${RED}%s${NC}\n" "Lua chon cua ban khong chinh xac. Vui long chon lai. $REPLY" ;;
        esac
    done
}

_select_site_enable_compress_image(){
    domain=""
    if [[ "$(ls -A "${USER_DIR}")" ]]; then
        domains=()
        echo "${LIST_DOMAIN}"
        _cd_dir "${USER_DIR}"
        for entry_img in .*.conf; do
            domain=${entry_img/./}
            domain=${domain//.conf/}
            if [ -f "${PAGESPEED_DIR}/${domain}/main.conf" ]; then
                check_compress_img=$(grep -w "compress_img.conf" "${PAGESPEED_DIR}/${domain}/main.conf")
                if [[ -z "${check_compress_img}" ]]; then
                    domains+=("${domain}")
                fi
            fi
        done

        if [ ${#domains[@]} -eq 0 ]; then
            ALERT=$(printf "%s\n" "${RED}Toan bo website da duoc bat Compress Image.${NC}")
        else
            echo "Lua chon website"
            PS3="${INPUT_SELECT} [0 = Thoat]: "
            select opt_img in "${domains[@]}"; do
                domain=$opt_img
                break
            done
        fi
    else
        ALERT=$(printf "%s\n" "${RED}Ban chua cau hinh ngx_pagespeed cho bat ky website nao.${NC}")
    fi
}

_select_site_disable_compress_image(){
    domain=""
    if [[ "$(ls -A "${USER_DIR}")" ]]; then
        domains=()
        echo "${LIST_DOMAIN}"
        _cd_dir "${USER_DIR}"
        for entry in .*.conf; do
            domain=${entry/./}
            domain=${domain//.conf/}
            if [ -f "${PAGESPEED_DIR}/${domain}/main.conf" ]; then
                check_compress_img=$(grep -w "compress_img.conf" "${PAGESPEED_DIR}/${domain}/main.conf")
                if [[ -n "${check_compress_img}" ]]; then
                    domains+=("${domain}")
                fi
            fi
        done

        if [ ${#domains[@]} -eq 0 ]; then
            ALERT=$(printf "%s\n" "${RED}Ban chua bat Compress Image cho bat ky website nao.${NC}")
        else
            echo "Lua chon website"
            PS3="${INPUT_SELECT} [0 = Thoat]: "
            select opt in "${domains[@]}"; do
                domain=$opt
                break
            done
        fi
    else
        ALERT=$(printf "%s\n" "${RED}Ban chua cau hinh ngx_pagespeed cho bat ky website nao.${NC}")
    fi
}

_enable_compress_image(){
    if [ ! -f "${PAGESPEED_DIR}/${domain}/compress_img.conf" ]; then
        if [ -f "${CUSTOM_DIR}/ngx_pagespeed/compress_img.conf" ]; then
            cp "${CUSTOM_DIR}"/ngx_pagespeed/compress_img.conf "${PAGESPEED_DIR}"/"${domain}"/compress_img.conf
        else
            cp "${TEMPLATE_DIR}"/ngx_pagespeed/compress_img.conf "${PAGESPEED_DIR}"/"${domain}"/compress_img.conf
        fi
    fi

    check_compress_img=$(grep -w "compress_img.conf" "${PAGESPEED_DIR}/${domain}/main.conf")
    if [ -z "${check_compress_img}" ]; then
        echo "include ${PAGESPEED_DIR}/${domain}/compress_img.conf;" >> "${PAGESPEED_DIR}"/"${domain}"/main.conf
    fi

    if nginx -t; then
        _restart_service
        clear
        printf "%s\n" "${GREEN}Bat Compress image thanh cong.${NC}"
    else
        clear
        nginx -t
        printf "%s\n" "${RED}Loi cau hinh Nginx. Vui long kiem tra lai.${NC}"
        printf "%s\n" "${RED}Ban co the su dung menu Rewrite Config (1 - 5) neu khong the tu sua loi.${NC}"
    fi
}

_disable_compress_image(){
    sed -i '/compress_img.conf/d' "${PAGESPEED_DIR}"/"${domain}"/main.conf

    if nginx -t; then
        _restart_service
        clear
        printf "%s\n" "${GREEN}Tat Compress Image thanh cong.${NC}"
    else
        clear
        nginx -t
        printf "%s\n" "${RED}Loi cau hinh Nginx. Vui long kiem tra lai.${NC}"
        printf "%s\n" "${RED}Ban co the su dung menu Rewrite Config (1 - 5) neu khong the tu sua loi.${NC}"
    fi
}

_run(){
    if [[ -z "${domain}" && -z "${ALERT}" ]]; then
        clear
        printf "%s\n" "${RED}Huy thao tac.${NC}"
    else
        if [ -z "${ALERT}" ]; then
            if [ "${action}" == "enable" ]; then
                _enable_compress_image
            else
                _disable_compress_image
            fi
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    fi
}

ALERT=""
domain=""
action=""

_select_action

if [[ "${action}" == "cancel" || -z "${action}" ]]; then
    clear
    printf "%s\n" "${RED}Huy thao tac.${NC}"
else
    if [ "${action}" == "enable" ]; then
        _select_site_enable_compress_image
    else
        _select_site_disable_compress_image
    fi

    _run
fi
