#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_select_action(){
    clear
    printf "%s\n" "Lua chon thao tac ban muon thuc hien"
    PS3="Nhap vao lua chon cua ban [ 1 - 3 ]: "
    options_css=("Enable Convert Image to Webp" "Disable Convert Image to Webp" "Cancel")
    select opt_webp in "${options_css[@]}"; do
        case $opt_webp in
        "Enable Convert Image to Webp")
            action="enable"
            break
            ;;
        "Disable Convert Image to Webp")
            action="disable"
            break
            ;;
        "Cancel")
            action="cancel"
            break
            ;;
        *) printf "${RED}%s${NC}\n" "Lua chon cua ban khong chinh xac. Vui long chon lai." ;;
        esac
    done
}

_select_site_enable_convert_img_to_webp(){
    domain=""
    if [[ "$(ls -A "${USER_DIR}")" ]]; then
        domains=()
        echo "${LIST_DOMAIN}"
        _cd_dir "${USER_DIR}"
        for entry_webp in .*.conf; do
            domain=${entry_webp/./}
            domain=${domain//.conf/}
            if [ -f "${PAGESPEED_DIR}/${domain}/main.conf" ]; then
                check_img_to_webp=$(grep -w "img_to_webp.conf" "${PAGESPEED_DIR}/${domain}/main.conf")
                if [[ -z "${check_img_to_webp}" ]]; then
                    domains+=("${domain}")
                fi
            fi
        done

        if [ ${#domains[@]} -eq 0 ]; then
            ALERT=$(printf "%s\n" "${RED}Toan bo website da duoc bat Convert Image.${NC}")
        else
            echo "Lua chon website"
            PS3="${INPUT_SELECT} [0 = Thoat]: "
            select opt_webp in "${domains[@]}"; do
                domain=$opt_webp
                break
            done
        fi
    else
        ALERT=$(printf "%s\n" "${RED}Ban chua cau hinh ngx_pagespeed cho bat ky website nao.${NC}")
    fi
}

_select_site_disable_convert_img_to_webp(){
    domain=""
    if [[ "$(ls -A "${USER_DIR}")" ]]; then
        domains=()
        echo "${LIST_DOMAIN}"
        _cd_dir "${USER_DIR}"
        for entry_webp in .*.conf; do
            domain=${entry_webp/./}
            domain=${domain//.conf/}
            if [ -f "${PAGESPEED_DIR}/${domain}/main.conf" ]; then
                check_img_to_webp=$(grep -w "img_to_webp.conf" "${PAGESPEED_DIR}/${domain}/main.conf")
                if [[ -n "${check_img_to_webp}" ]]; then
                    domains+=("${domain}")
                fi
            fi
        done

        if [ ${#domains[@]} -eq 0 ]; then
            ALERT=$(printf "%s\n" "${RED}Ban chua bat Convert Image cho bat ky website nao.${NC}")
        else
            echo "Lua chon website"
            PS3="${INPUT_SELECT} [0 = Thoat]: "
            select opt_webp in "${domains[@]}"; do
                domain=$opt_webp
                break
            done
        fi
    else
        ALERT=$(printf "%s\n" "${RED}Ban chua cau hinh ngx_pagespeed cho bat ky website nao.${NC}")
    fi
}

_enable_convert_img_to_webp(){
    if [ ! -f "${PAGESPEED_DIR}/${domain}/img_to_webp.conf" ]; then
        if [ -f "${CUSTOM_DIR}/ngx_pagespeed/img_to_webp.conf" ]; then
            cp "${CUSTOM_DIR}"/ngx_pagespeed/img_to_webp.conf "${PAGESPEED_DIR}"/"${domain}"/img_to_webp.conf
        else
            cp "${TEMPLATE_DIR}"/ngx_pagespeed/img_to_webp.conf "${PAGESPEED_DIR}"/"${domain}"/img_to_webp.conf
        fi
    fi

    check_img_to_webp=$(grep -w "img_to_webp.conf" "${PAGESPEED_DIR}/${domain}/main.conf")
    if [ -z "${check_img_to_webp}" ]; then
        echo "include ${PAGESPEED_DIR}/${domain}/img_to_webp.conf;" >> "${PAGESPEED_DIR}"/"${domain}"/main.conf
    fi

    if nginx -t; then
        _restart_service
        clear
        printf "%s\n" "${GREEN}Bat Convert Image To Webp thanh cong.${NC}"
    else
        clear
        nginx -t
        printf "%s\n" "${RED}${lang_error_vhost}${NC}"
        printf "%s\n" "${RED}${lang_use_rewrite_config}${NC}"
    fi
}

_disable_convert_img_to_webp(){
    sed -i '/img_to_webp.conf/d' "${PAGESPEED_DIR}"/"${domain}"/main.conf

    if nginx -t; then
        _restart_service
        clear
        printf "%s\n" "${GREEN}Tat Convert Image To Webp thanh cong.${NC}"
    else
        clear
        nginx -t
        printf "%s\n" "${RED}Loi cau hinh Nginx. Vui long kiem tra lai.${NC}"
        printf "%s\n" "${RED}Ban co the su dung menu Rewrite Config (1 - 5) neu khong the tu sua loi.${NC}"
    fi
}

_run(){
    if [[ -z "${domain}" && -z "${ALERT}" ]]; then
        clear
        printf "%s\n" "${RED}Huy thao tac.${NC}"
    else
        if [ -z "${ALERT}" ]; then
            if [ "${action}" == "enable" ]; then
                _enable_convert_img_to_webp
            else
                _disable_convert_img_to_webp
            fi
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    fi
}

ALERT=""
domain=""
action=""

_select_action

if [[ "${action}" == "cancel" || -z "${action}" ]]; then
    clear
    printf "%s\n" "${RED}Huy thao tac.${NC}"
else
    if [ "${action}" == "enable" ]; then
        _select_site_enable_convert_img_to_webp
    else
        _select_site_disable_convert_img_to_webp
    fi

    _run
fi
