#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_select_action(){
    clear
    printf "%s\n" "Lua chon thao tac ban muon thuc hien"
    PS3="Nhap vao lua chon cua ban [ 1 - 3 ]: "
    options_html=("Enable Minify HTML" "Disable Minify HTML" "Cancel")
    select opt_html in "${options_html[@]}"; do
        case $opt_html in
        "Enable Minify HTML")
            action="enable"
            break
            ;;
        "Disable Minify HTML")
            action="disable"
            break
            ;;
        "Cancel")
            action="cancel"
            break
            ;;
        *) printf "${RED}%s${NC}\n" "Lua chon cua ban khong chinh xac. Vui long chon lai." ;;
        esac
    done
}

_select_site_enable_minify_html(){
    domain=""
    if [[ "$(ls -A "${USER_DIR}")" ]]; then
        domains=()
        echo "${LIST_DOMAIN}"
        _cd_dir "${USER_DIR}"
        for entry_html in .*.conf; do
            domain=${entry_html/./}
            domain=${domain//.conf/}
            if [ -f "${PAGESPEED_DIR}/${domain}/main.conf" ]; then
                check_minify_html=$(grep -w "minify_html.conf" "${PAGESPEED_DIR}/${domain}/main.conf")
                if [[ -z "${check_minify_html}" ]]; then
                    domains+=("${domain}")
                fi
            fi
        done

        if [ ${#domains[@]} -eq 0 ]; then
            ALERT=$(printf "%s\n" "${RED}Toan bo website da duoc bat Minify HTML.${NC}")
        else
            echo "Lua chon website"
            PS3="${INPUT_SELECT} [0 = Thoat]: "
            select opt_html in "${domains[@]}"; do
                domain=$opt_html
                break
            done
        fi
    else
        ALERT=$(printf "%s\n" "${RED}Ban chua cau hinh ngx_pagespeed cho bat ky website nao.${NC}")
    fi
}

_select_site_disable_minify_html(){
    domain=""
    if [[ "$(ls -A "${USER_DIR}")" ]]; then
        domains=()
        echo "${LIST_DOMAIN}"
        _cd_dir "${USER_DIR}"
        for entry in .*.conf; do
            domain=${entry/./}
            domain=${domain//.conf/}
            if [ -f "${PAGESPEED_DIR}/${domain}/main.conf" ]; then
                check_minify_html=$(grep -w "minify_html.conf" "${PAGESPEED_DIR}/${domain}/main.conf")
                if [[ -n "${check_minify_html}" ]]; then
                    domains+=("${domain}")
                fi
            fi
        done

        if [ ${#domains[@]} -eq 0 ]; then
            ALERT=$(printf "%s\n" "${RED}Ban chua bat Minify HTML cho bat ky website nao.${NC}")
        else
            echo "Lua chon website"
            PS3="${INPUT_SELECT} [0 = Thoat]: "
            select opt in "${domains[@]}"; do
                domain=$opt
                break
            done
        fi
    else
        ALERT=$(printf "%s\n" "${RED}Ban chua cau hinh ngx_pagespeed cho bat ky website nao.${NC}")
    fi
}

_enable_minify_html(){
    if [ ! -f "${PAGESPEED_DIR}/${domain}/minify_html.conf" ]; then
        if [ -f "${CUSTOM_DIR}/ngx_pagespeed/minify_html.conf" ]; then
            cp "${CUSTOM_DIR}"/ngx_pagespeed/minify_html.conf "${PAGESPEED_DIR}"/"${domain}"/minify_html.conf
        else
            cp "${TEMPLATE_DIR}"/ngx_pagespeed/minify_html.conf "${PAGESPEED_DIR}"/"${domain}"/minify_html.conf
        fi
    fi

    check_minify_html=$(grep -w "minify_html.conf" "${PAGESPEED_DIR}/${domain}/main.conf")
    if [ -z "${check_minify_html}" ]; then
        echo "include ${PAGESPEED_DIR}/${domain}/minify_html.conf;" >> "${PAGESPEED_DIR}"/"${domain}"/main.conf
    fi

    if nginx -t; then
        _restart_service
        clear
        printf "%s\n" "${GREEN}Bat Minify HTML thanh cong.${NC}"
    else
        clear
        nginx -t
        printf "%s\n" "${RED}${lang_error_vhost}${NC}"
        printf "%s\n" "${RED}${lang_use_rewrite_config}${NC}"
    fi
}

_disable_minify_html(){
    sed -i '/minify_html.conf/d' "${PAGESPEED_DIR}"/"${domain}"/main.conf

    if nginx -t; then
        _restart_service
        clear
        printf "%s\n" "${GREEN}Tat Minify HTML thanh cong.${NC}"
    else
        clear
        nginx -t
        printf "%s\n" "${RED}${lang_error_vhost}${NC}"
        printf "%s\n" "${RED}${lang_use_rewrite_config}${NC}"
    fi
}

_run(){
    if [[ -z "${domain}" && -z "${ALERT}" ]]; then
        clear
        printf "%s\n" "${RED}Huy thao tac.${NC}"
    else
        if [ -z "${ALERT}" ]; then
            if [ "${action}" == "enable" ]; then
                _enable_minify_html
            else
                _disable_minify_html
            fi
        else
            clear
            printf "%s\n" "${ALERT}"
        fi
    fi
}

ALERT=""
domain=""
action=""

_select_action

if [[ "${action}" == "cancel" || -z "${action}" ]]; then
    clear
    printf "%s\n" "${RED}Huy thao tac.${NC}"
else
    if [ "${action}" == "enable" ]; then
        _select_site_enable_minify_html
    else
        _select_site_disable_minify_html
    fi

    _run
fi
