#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

printf "%s\n" "${GREEN}======================${NC}"
printf "%s\n" "${GREEN}Phan quyen Chown/Chmod${NC}"
printf "%s\n" "${GREEN}======================${NC}"

#https://www.cyberciti.biz/faq/linux-unix-shell-check-if-directory-empty/
if [ "$(ls -A "${USER_DIR}")" ]; then
    clear
    echo "Dang phan quyen cho cac domain. Vui long doi..."
    sleep 1
    _cd_dir "/var/hostvn/users"
    for entry in .*.conf; do
        domain=${entry/.}
        domain=${domain//.conf}
        #https://www.howtoforge.com/tutorial/linux-grep-command/
        #https://stackoverflow.com/a/6284370
        user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
        chmod 711 /home
        chmod 755 /home/"${user}"
        chmod 711 /home/"${user}"/"${domain}"
        chmod 711 /home/"${user}"/"${domain}"/logs
        chmod 755 /home/"${user}"/"${domain}"/public_html
        find /home/"${user}"/"${domain}"/public_html/ -type d -print0 | xargs -I {} -0 chmod 0755 {}
        find /home/"${user}"/"${domain}"/public_html/ -type f -print0 | xargs -I {} -0 chmod 0644 {}
        chown root:root /home/"${user}"
        chown -R "${user}":"${user}" /home/"${user}"/"${domain}"
        chown -R "${user}":"${user}" /home/"${user}"/tmp
        chown -R "${user}":"${user}" /home/"${user}"/php
    done
    printf "%s\n" "${GREEN}Phan quyen hoan tat.${NC}"
else
    clear
    printf "%s\n" "${RED}Khong co Domain nao ton tai tren he thong.${NC}"
fi

# shellcheck disable=SC2034
CHOICE=0
menu_permission
