#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

# shellcheck disable=SC2154
# shellcheck disable=SC1091
source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

printf "%s\n" "${GREEN}======================${NC}"
printf "%s\n" "${GREEN}Phan quyen Chown/Chmod${NC}"
printf "%s\n" "${GREEN}======================${NC}"

_run(){
    while true
    do
        read -r -p "Xac nhan phan quyen cho ten mien: ${domain}? (y/n): " confirm
        echo
        if [[ "${confirm}" =~ ^([yY])$ || "${confirm}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n"  "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done

    if [[ "$confirm" =~ ^([yY])$ ]]; then
        echo "Dang tien hanh phan quyen. Vui long doi..."
        #https://www.howtoforge.com/tutorial/linux-grep-command/
        #https://stackoverflow.com/a/6284370
        user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
        chmod 711 /home
        chmod 755 /home/"${user}"
        chmod 711 /home/"${user}"/"${domain}"
        chmod 711 /home/"${user}"/"${domain}"/logs
        chmod 755 /home/"${user}"/"${domain}"/public_html
        find /home/"${user}"/"${domain}"/public_html/ -type d -print0 | xargs -I {} -0 chmod 0755 {}
        find /home/"${user}"/"${domain}"/public_html/ -type f -print0 | xargs -I {} -0 chmod 0644 {}
        chown root:root /home/"${user}"
        chown -R "${user}":"${user}" /home/"${user}"/"${domain}"
        chown -R "${user}":"${user}" /home/"${user}"/tmp
        chown -R "${user}":"${user}" /home/"${user}"/php
        clear
        printf "%s\n" "${GREEN}Da phan quyen cho website: ${domain}.${NC}"
    else
        clear
        printf "%s\n" "${RED}Huy phan quyen.${NC}"
    fi
}

confirm=""
domain=""
clear
_select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_permission
