#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_confirm_delete_backup() {
    while true; do
        read -r -p "Ban muon xoa backup ? (y/n) " prompt_delete
        echo
        if [[ "${prompt_delete}" =~ ^([yY])$ || "${prompt_delete}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n" "${RED}Gia tri khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

_select_backup_location() {
    clear
    printf "%s\n" "Lua chon noi luu backup"
    PS3="Nhap vao lua chon cua ban [ 1 - 3 ]: "
    location_options=("VPS (Local)" "Google Drive" "Cancel")
    select opt_location in "${location_options[@]}"; do
        case $opt_location in
        "VPS (Local)")
            location="local"
            break
            ;;
        "Google Drive")
            location="drive"
            break
            ;;
        "Cancel")
            location="cancel"
            break
            ;;
        *) printf "${RED}%s${NC}\n" "Lua chon cua ban khong chinh xac. Vui long chon lai. $REPLY" ;;
        esac
    done
}

_delete_backup() {
    if [ "${location}" == "local" ]; then
        _list_backup
        if [[ -z "${date}" || -z "${domain}" ]]; then
            clear
            printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
        else
            if [ -z "${domain}" ]; then
                clear
                printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
            else
                if [[ -z "${ALERT}" ]]; then
                    rm -rf /home/backup/"${date}"/"${domain}"/*
                    clear
                    printf "%s\n" "${GREEN}Xoa backup thanh cong.${NC}"
                else
                    clear
                    printf "%s\n" "${ALERT}"
                fi
            fi
        fi
    else
        _select_remote
        if [ -z "${remote}" ]; then
            clear
            printf "${RED}%s${NC}\n" "Huy thao tac."
        else
            echo "Chon ngay ban muon xoa: "
            selects_date=$(rclone lsf "${remote}":"${IPADDRESS}")
            dates=()
            for entry_date in ${selects_date}; do
                select_date=${entry_date///}
                dates+=("${select_date}")
            done
            PS3="Nhap lua chon cua ban [0 = Thoat]: "
            select date in "${dates[@]}"; do
                date=${date}
                break
            done

            if [ -z "${date}" ]; then
                clear
                printf "${RED}%s${NC}\n" "Huy thao tac."
            else
                echo "Chon ten mien ban muon xoa: "
                selects_domain=$(rclone lsf "${remote}":"${IPADDRESS}"/"${date}")
                domains=()
                for entry_domain in ${selects_domain}; do
                    select_domain=${entry_domain///}
                    domains+=("${select_domain}")
                done
                PS3="Nhap lua chon cua ban [0 = Thoat]: "
                select domain in "${domains[@]}"; do
                    domain=${domain}
                    break
                done
                if [ -z "${domain}" ]; then
                    clear
                    printf "${RED}%s${NC}\n" "Huy thao tac."
                else
                    rclone delete "${remote}":/"${IPADDRESS}"/"${date}"/"${domain}" --rmdirs >/dev/null 2>&1
                    rclone cleanup "${remote}":"${IPADDRESS}" >/dev/null 2>&1
                    rm -rf /home/backup/"${date}"/"${domain}"
                    clear
                    printf "%s\n" "${GREEN}Xoa backup thanh cong.${NC}"
                fi
            fi
        fi
    fi
}

clear

prompt_delete="n"
location="cancel"
date=""
domain=""

_confirm_delete_backup

if [[ "${prompt_delete}" =~ ^([yY])$ || "${prompt_delete}" =~ ^([nN])$ ]]; then
    _select_backup_location
    if [[ -z "${location}" || "${location}" == "cancel" ]]; then
        clear
        printf "${RED}%s${NC}\n" "Huy thao tac."
    else
        if [[ "${location}" == "drive" && ! -f "/root/.config/rclone/rclone.conf" ]]; then
            clear
            printf "${RED}%s${NC}\n" "Ban chua tao ket noi toi Google Drive."
        else
            _delete_backup
        fi
    fi
else
    clear
    printf "${RED}%s${NC}\n" "Huy thao tac."
fi

menu_backup
