#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_run(){
    string1=$(grep -rnw "/etc/php/${php1_version}/fpm/conf.d/opcache-default.blacklist" -e "${domain}")
    user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=');
    if [ -z "${string1}" ]; then
        echo "/home/${user}/${domain}/public_html/*" >> /etc/php/"${php1_version}"/fpm/conf.d/opcache-default.blacklist
        systemctl restart php"${php1_version}"-fpm
    fi

    if [ "${php2_release}" == "yes" ]; then
        string2=$(grep -rnw "/etc/php/${php2_version}/fpm/conf.d/opcache-default.blacklist" -e "${domain}")
        if [ -z "$string2" ]; then
            echo "/home/${user}/${domain}/public_html/*" >> /etc/php/"${php2_version}"/fpm/conf.d/opcache-default.blacklist
            systemctl restart php"${php2_version}"-fpm
        fi
    fi

    clear
    printf "%s\n" "${GREEN}Them website vao blacklist thanh cong.${NC}"
}

domain=""
ALERT=""

_select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy thao tac${NC}"
else
    if [ -z "${ALERT}" ]; then
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

cache_manage_opcache
