#!/bin/bash

######################################################################
#           Auto Install & Optimize LEMP Stack on Ubuntu             #
#                                                                    #
#                Author: Sanvv - HOSTVN Technical                    #
#                  Website: https://hostvn.vn                        #
#                                                                    #
#              Please do not remove copyright. Thank!                #
#  Please do not copy under any circumstance for commercial reason!  #
######################################################################

source /var/hostvn/menu/validate/rule
source /var/hostvn/menu/helpers/function

_backup_confirm() {
    while true; do
        read -r -p "Ban co muon backup du lieu truoc khi toi uu khong? (y/n) " prompt_backup
        echo
        if [[ "${prompt_backup}" =~ ^([yY])$ || "${prompt_backup}" =~ ^([nN])$ ]]; then
            break
        else
            printf "%s\n" "${RED}Gia tri ban nhap khong chinh xac. Vui long nhap lai.${NC}"
        fi
    done
}

_backup() {
    if [[ ! -d "/home/backup/${CURRENT_DATE}/${domain}" ]]; then
        mkdir -p /home/backup/"${CURRENT_DATE}"/"${domain}"
    fi
    _cd_dir /home/"${user}"/"${domain}"
    if [ -f "/home/backup/${CURRENT_DATE}/${domain}/${domain}.tar.gz" ]; then
        rm -rf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz
    fi
    tar -cpzvf /home/backup/"${CURRENT_DATE}"/"${domain}"/"${domain}".tar.gz \
        --exclude "public_html/wp-content/cache" --exclude "public_html/storage/framework/*" \
        --exclude "public_html/storage/logs/*" public_html
}

_run() {
    if [ -d "/home/${user}/${domain}/public_html/wp-content/uploads" ]; then
        before_compress=$(du -sh /home/"${user}"/"${domain}"/public_html/wp-content/uploads | cut -f1 -d"/")
        clear
        printf "%s\n" "${GREEN}Dang toi uu anh, vui long doi den khi qua trinh nen anh hoan tat...${NC}"
        find /home/"${user}"/"${domain}"/public_html/wp-content/uploads -type f -size +100k -iname "*.png" -exec pngquant --quality=75-80 --ext=.png --force {} \;
        find /home/"${user}"/"${domain}"/public_html/wp-content/uploads -type f -size +100k \( -iname "*.jpg" -o -iname "*.jpeg" \) -exec jpegoptim -s -m 75 -f --strip-all {} \;

        find /home/"${user}"/"${domain}"/public_html/wp-content/upload -type d -print0 | xargs -I {} -0 chmod 0755 {}
        find /home/"${user}"/"${domain}"/public_html/wp-content/upload -type f -print0 | xargs -I {} -0 chmod 0644 {}

        after_compress=$(du -sh /home/"${user}"/"${domain}"/public_html/wp-content/uploads | cut -f1 -d"/")
        clear
        printf "%s\n" "${GREEN}Toi uu hinh anh thanh cong${NC}"
        printf "%s\n" "${GREEN}Dung luong truoc khi toi uu:${NC} ${RED}${before_compress}${NC}"
        printf "%s\n" "${GREEN}Dung luong sau khi toi uu:${NC} ${RED}${after_compress}${NC}"
    else
        while true; do
            echo "Nhap vao duong dan thu muc chua anh. Vi du: Voi Laravel co the nhap: public/uploads"
            read -r -p "Nhap duong dan toi thu muc chua anh [0 = Thoat]: " uploads_path
            echo
            if [[ -d "/home/${user}/${domain}/public_html/${uploads_path}" || "${uploads_path}" == "0" ]]; then
                break
            else
                printf "%s\n" "${RED}Duong dan khong ton tai. Vui long nhap lai.${NC}"
            fi
        done

        if [ "${uploads_path}" == "0" ]; then
            clear
            printf "%s\n" "${RED}Ban da chon huy hanh dong.${NC}"
        else
            before_compress=$(du -sh /home/"${user}"/"${domain}"/public_html/"${uploads_path}" | cut -f1 -d"/")
            clear
            printf "%s\n" "${GREEN}Dang toi uu anh, vui long doi...${NC}"
            find /home/"${user}"/"${domain}"/public_html/"${uploads_path}" -type f -size +100k -iname "*.png" -exec pngquant --quality=75-80 --ext=.png --force {} \;
            find /home/"${user}"/"${domain}"/public_html/"${uploads_path}" -type f -size +100k \( -iname "*.jpg" -o -iname "*.jpeg" \) -exec jpegoptim -m 75 -f --strip-all {} \;

            find /home/"${user}"/"${domain}"/public_html/"${uploads_path}" -type d -print0 | xargs -I {} -0 chmod 0755 {}
            find /home/"${user}"/"${domain}"/public_html/"${uploads_path}" -type f -print0 | xargs -I {} -0 chmod 0644 {}

            after_compress=$(du -sh /home/"${user}"/"${domain}"/public_html/"${uploads_path}" | cut -f1 -d"/")
            clear
            printf "%s\n" "${GREEN}Toi uu hinh anh thanh cong${NC}"
            printf "%s\n" "${GREEN}Dung luong truoc khi toi uu:${NC} ${RED}${before_compress}${NC}"
            printf "%s\n" "${GREEN}Dung luong sau khi toi uu:${NC} ${RED}${after_compress}${NC}"
        fi
    fi
}

domain=""
prompt_backup=""
uploads_path=""
before_compress=""
after_compress=""
ALERT=""

_select_domain

if [[ -z "${domain}" && -z "${ALERT}" ]]; then
    clear
    printf "%s\n" "${RED}Ban da chon huy hanh dong.${NC}"
else
    if [ -z "${ALERT}" ]; then
        user=$(grep -w "username" "${USER_DIR}/.${domain}.conf" | cut -f2 -d'=')
        _backup_confirm
        if [[ "${prompt_backup}" =~ ^([yY])$ ]]; then
            _make_backup_dir "${domain}"
            _backup
        fi
        _run
    else
        clear
        printf "%s\n" "${ALERT}"
    fi
fi

menu_tools
